### ISSUE TITLE
USB to CAN board

### ISSUE THREAD

**Issue by jameschen1999** [kcaluwae/dspic33e-bootloader#3]
Ken,

For the host program, I plan to use the '-m python' flag: python dspic33E_bootloader.py -u -n 3 -m python dspic_main_example.production.hex

What did you use for the USB to CAN adaptor board?  Can I use PCAN-USB adapter https://www.peak-system.com/PCAN-USB.199.0.html?&L=1 ?

Thanks for the help!

Jian

**Comment by kcaluwae** [comment]
Hi Jian,

We used the built-in CAN hardware on the Beaglebone Black, but I'm guessing the PCAN-USB adapter should work fine too.

Ken

**Comment by jameschen1999** [comment]
Hi Ken,

I will try it.  Thanks for the response!

Jian
